---
blank_issues_enabled: false
contact_links:
  - name: Exam AZ-303 Microsoft Azure Architect Technologies Crash Course Community Support
    url: https://github.com/timothywarner/az303/discussions
    about: Please ask and answer questions here.
